from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('members/<int:chama_id>/', views.members, name='members'),
    path('contributions/', views.contributions, name='contributions'),
    path('loans/<int:member_id>/<int:chama_id>/<int:amount>/<str:loan_type>/', views.loans, name='loans'),
    path('postsignIn/<str:email>/<str:password>/<str:chama>/', views.postsignIn, name='postsignIn'),
    path('logout/', views.logout, name='logout'),
    path('postsignUp/', views.postsignUp, name='postsignUp'),
    path('postReset/<str:email>/', views.postReset, name='postReset'),
    path('createchama/', views.createchama, name='createchama'),
    path('getMember/<str:email>/<str:chama>/', views.getMember, name='getMember'),
    path('getChama/<str:email>/', views.getChama, name='getChama'),
    path('allchamas/', views.allchamas, name='allchamas'),
    path('getLoans/<int:chama_id>/<str:email>/', views.getLoans, name='getLoans'),
    path('getloanrepayment/<str:chamaname>/<int:member_id>/', views.getloanrepayment, name='getloanrepayment'),
    path('getContributions/<int:chama_id>/<int:member_id>/', views.getContributions, name='getContributions'),
    path('getAllLoans/<str:role>/<int:chama_id>/', views.getAllLoans, name='getAllLoans'),
    path('get_notifications/<str:email>/<int:chama_id>/', views.get_notifications, name='get_notifications'),
    path('transactions/<str:transaction_type>/<str:email>/<int:chama_id>/', views.transactions, name='transactions'),
    path('totalchamamembers/<str:chama>/', views.totalchamamembers, name='totalchamamembers'),
    path('totalchamasavings/<int:chama_id>/', views.totalchamasavings, name='totalchamasavings'),
    path('totalchamaloans/<int:chama_id>/', views.totalchamaloans, name='totalchamaloans'),
    path('payloan/', views.payloan, name='payloan'),
    path('getmemberscontribution/<int:chama_id>/', views.getmemberscontribution, name='getmemberscontribution'),
    path('joinchama/<int:member_id>/<str:chama_name>/', views.joinchama, name='joinchama'),
    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('changeroles/<int:chama_id>/<int:chairperson_id>/<int:treasurer_id>/<int:secretary_id>/', views.changeroles, name='changeroles'),
    path('send_mpesa_payout/<str:phone_number>/<str:name>/<int:amount_kes>/<str:reason>/', views.send_mpesa_payout, name='send_mpesa_payout'),
    path('insurance/', views.insurance, name='insurance'),
    path('get_total_insurance/<int:member_id>/<int:chama_id>/', views.get_total_insurance, name='get_total_insurance'),
    path('get_all_chamas/', views.get_all_chamas, name='get_all_chamas'),
    path('get_all_members/', views.get_all_members, name='get_all_members'),
    path('get_member_chamas/<str:email>/', views.get_member_chamas, name='get_member_chamas'),
]