# Generated by Django 5.1.6 on 2025-02-14 08:41

import backend_app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamas',
            fields=[
                ('chama_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('event', 'Event'), ('emergency', 'Emergency')], default='personal', max_length=20)),
                ('notification', models.CharField(default='Greetings, testing app', max_length=1000)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('emergency', 'Emergency Loan')], default='personal', max_length=20)),
                ('loan_status', models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=20)),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('loan_deadline', models.DateTimeField(validators=[backend_app.models.validate_date])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
    ]
