# Generated by Django 5.1.6 on 2025-02-26 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamas',
            name='created_by',
            field=models.CharField(default='chamavault', max_length=200),
        ),
        migrations.AddField(
            model_name='chamas',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chamas',
            name='description',
            field=models.TextField(default='This chama was created by chamavault', max_length=500),
        ),
    ]
