# Generated by Django 5.1.6 on 2025-02-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_chamas_created_by_chamas_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='member',
        ),
        migrations.AddField(
            model_name='loans',
            name='approved_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='backend_app.members'),
        ),
        migrations.AddField(
            model_name='loans',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
        migrations.AddField(
            model_name='loans',
            name='name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='loanee_name', to='backend_app.members'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_type',
            field=models.CharField(choices=[('LTL', 'Long Term Loan'), ('STL', 'Short Term Loan')], default='LTL', max_length=20),
        ),
    ]
