# Generated by Django 5.1.6 on 2025-03-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_contributions_chama_contributions_penality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members'),
        ),
    ]
