# Generated by Django 5.1.6 on 2025-03-14 20:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_notifications_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_type', models.CharField(choices=[('real estate', 'real estate'), ('stock', 'stock')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed')], max_length=20)),
                ('investment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=128)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='investment_contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.investment')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='profit_distribution',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.investment')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
    ]
