# Generated by Django 5.1.6 on 2025-04-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_investment_contribution_investment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='transactionRef',
            field=models.CharField(default='T073397058487061', max_length=50),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transactionRef',
            field=models.CharField(default='T073397058487061', max_length=50),
        ),
        migrations.AlterField(
            model_name='loans',
            name='approved_by',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='backend_app.members'),
        ),
    ]
