# Generated by Django 5.1.6 on 2025-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_contributions_transactionref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('chairperson', 'chairperson'), ('treasurer', 'treasurer'), ('secretary', 'secretary')], default='member', max_length=20),
        ),
    ]
