# Generated by Django 5.1.6 on 2025-04-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_members_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('loanapproval_id', models.AutoField(primary_key=True, serialize=False)),
                ('chairperson_approval', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default='pending', max_length=45)),
                ('treasurer_approval', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default='pending', max_length=45)),
                ('secretary_approval', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default='pending', max_length=45)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.loans')),
            ],
        ),
    ]
