# Generated by Django 5.1.6 on 2025-04-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_creditscore_loanapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loan_status',
        ),
    ]
