# Generated by Django 5.1.6 on 2025-04-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_poll_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.choice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.poll')),
            ],
        ),
    ]
