# Generated by Django 5.1.6 on 2025-04-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_memberpoll_chama_poll_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('agenda', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
            ],
        ),
    ]
