# Generated by Django 5.1.6 on 2025-04-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_notifications_chama_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='name',
            new_name='member',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
    ]
