# Generated by Django 5.1.6 on 2025-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_rename_name_loanrepayment_member_loanrepayment_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='transactionRef',
            field=models.CharField(default='T073397058487061', max_length=50),
        ),
    ]
