# Generated by Django 5.1.6 on 2025-04-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_loanrepayment_transactionref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_id',
        ),
    ]
