# Generated by Django 5.1.6 on 2025-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_remove_loanrepayment_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expense_name',
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('rent', 'rent'), ('travel', 'travel'), ('business', 'business'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
