# Generated by Django 5.1.6 on 2025-04-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_remove_expenses_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
    ]
