# Generated by Django 5.1.6 on 2025-04-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_message_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_contribution',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
    ]
