# Generated by Django 5.1.6 on 2025-04-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_profit_distribution_chama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit_distribution',
            name='investment_id',
        ),
        migrations.AddField(
            model_name='profit_distribution',
            name='investment_contribution_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.investment_contribution'),
        ),
    ]
