# Generated by Django 5.1.6 on 2025-04-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_remove_profit_distribution_investment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_contribution',
            name='transactionRef',
            field=models.CharField(default='T073397058487061', max_length=50),
        ),
    ]
