# Generated by Django 5.1.6 on 2025-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_investment_contribution_transactionref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Loan repayment', 'Loan repayment'), ('Loan', 'Loan'), ('Expense', 'Expense'), ('Expense', 'Expense'), ('Investment', 'Investment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
