# Generated by Django 5.1.6 on 2025-04-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas'),
        ),
    ]
