# Generated by Django 5.1.6 on 2025-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0028_alter_members_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loans',
            name='repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
