# Generated by Django 5.1.6 on 2025-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_loans_loan_status_loans_repayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='loan_type',
            field=models.CharField(choices=[('LTL', 'Long Term Loan'), ('STL', 'Short Term Loan')], default='STL', max_length=20),
        ),
    ]
