# Generated by Django 5.1.6 on 2025-05-02 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0031_memberslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionDate',
            fields=[
                ('contribution_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
            ],
        ),
    ]
