# Generated by Django 5.1.6 on 2025-05-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0032_contributiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.members'),
        ),
    ]
