# Generated by Django 5.1.6 on 2025-05-07 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0033_alter_notifications_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='last_penalty_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
