# Generated by Django 5.1.6 on 2025-05-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_remove_contributions_last_penalty_date_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='penality',
        ),
    ]
