# Generated by Django 5.1.6 on 2025-05-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_remove_contributions_penality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaulters',
            fields=[
                ('defaulter_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('chama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
    ]
