# Generated by Django 5.1.6 on 2025-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0037_defaulters'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile_image',
            field=models.URLField(default='https://i.pravatar.cc/150?img=3'),
        ),
    ]
