# Generated by Django 5.1.6 on 2025-05-14 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0038_members_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_contribution',
            name='investment_id',
        ),
        migrations.RemoveField(
            model_name='investment_contribution',
            name='chama',
        ),
        migrations.RemoveField(
            model_name='investment_contribution',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='profit_distribution',
            name='investment_contribution_id',
        ),
        migrations.RemoveField(
            model_name='profit_distribution',
            name='chama',
        ),
        migrations.RemoveField(
            model_name='profit_distribution',
            name='member_id',
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(default='New Investment', max_length=100)),
                ('description', models.TextField(default='A new Project')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.IntegerField(default=0)),
                ('image', models.URLField(default='https://via.placeholder.com/300x200.png?text=Investment+Image')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.investments')),
            ],
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='investment_contribution',
        ),
        migrations.DeleteModel(
            name='profit_distribution',
        ),
    ]
