# Generated by Django 5.1.6 on 2025-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0039_remove_investment_contribution_investment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
