# Generated by Django 5.1.6 on 2025-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0040_alter_investments_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentcontribution',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
