# Generated by Django 5.1.6 on 2025-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0041_investmentcontribution_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentcontribution',
            name='transactionRef',
            field=models.CharField(default='T073397058487061', max_length=50),
        ),
    ]
