# Generated by Django 5.1.6 on 2025-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0042_investmentcontribution_transactionref'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
