# Generated by Django 5.1.6 on 2025-05-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0043_members_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.members'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Travel', 'Travel'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
