# Generated by Django 5.1.6 on 2025-05-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0044_expenses_member_alter_expenses_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='backend_app.loans'),
        ),
    ]
