# Generated by Django 5.1.6 on 2025-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0045_loanrepayment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='contribution_type',
            field=models.CharField(choices=[('ordinary', 'ordinary'), ('education', 'education')], default='contribution', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('chairperson', 'chairperson'), ('treasurer', 'treasurer'), ('secretary', 'secretary'), ('admin', 'admin')], default='member', max_length=20),
        ),
    ]
