# Generated by Django 5.1.6 on 2025-05-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0046_contributions_contribution_type_alter_members_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Loan repayment', 'Loan repayment'), ('Loan', 'Loan'), ('Expense', 'Expense'), ('Expense', 'Expense'), ('Insurance', 'Insurance'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('transactionRef', models.CharField(default='T073397058487061', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_date', models.DateTimeField(auto_now_add=True)),
                ('chama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.chamas')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.members')),
            ],
        ),
    ]
