# Generated by Django 5.1.6 on 2025-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0047_alter_transactions_transaction_type_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
