# Generated by Django 5.1.6 on 2025-05-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0048_loans_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='amount_paid',
        ),
    ]
