# Generated by Django 5.1.6 on 2025-05-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0049_remove_loans_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='id_number',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='profile_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
    ]
